In [1]:
import numpy as np

In [7]:
arr=np.array([1,2,3])
print(arr, type(arr), arr*2)

[1 2 3] <class 'numpy.ndarray'> [2 4 6]


In [8]:
#插入元素
arr[0]=100.9
print(arr)

[100   2   3]


In [5]:
#数组整体类型转换
arr2=arr.astype(float)
print(arr2)

[100.   2.   3.]


In [5]:
#参数是元组，表示数组形状。此处创建了一个三维数组。
arr3=np.ones((1,2,3))
print('三维数组',arr3)
print('形状',arr3.shape)
print('二维数组',np.zeros((2,3)))
print('二维数组',np.ones((2,2))*1.1)

三维数组 [[[1. 1. 1.]
  [1. 1. 1.]]]
形状 (1, 2, 3)
二维数组 [[0. 0. 0.]
 [0. 0. 0.]]
二维数组 [[1.1 1.1]
 [1.1 1.1]]


In [9]:
#一维数组升级为二维数组(元组第二个数字 -1表示自行运算)
arr4=arr3.reshape((1,-1))
print(arr4)
print(arr4.reshape(-1))

[[1. 1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1.]


In [15]:
arr5=np.arange(10)
print(arr5)
print(arr5.reshape(2,5))
print(arr5.reshape(2,5).reshape(-1))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [25]:
#1~22数组，步长为3（不包含右边界22）
arr6=np.arange(1,22,3)
print(arr6)

[ 1  4  7 10 13 16 19]


In [7]:
print(np.random.random((2,3))*40+ 60)
print(np.random.randint(10, 100, (2,3)))

X= np.random.rand(5, 1) # (0,1)间均匀分布随机数，形状(100*1)
Y= np.random.randn(5, 1) # 标准正态分布（均值为0，标准差为1）的随机数
print('X:', X)
print('NumPy 2*X:', 2*X)
print('N(0,1) Y:', Y)

'''NumPy 采用了不同的广播机制和操作规则，与 Python 的列表操作不同。
   NumPy会把内部每个元素乘a，而Python的list会直接复制a遍。'''
testList= [1,2,3]
print('Python list*2', testList*2) # 长度变成2倍
testList= [x * 2 for x in testList] # 变成2倍
print(testList)

[[65.34520786 81.98083484 61.13054657]
 [90.05093657 69.73268917 90.10906508]]
[[26 49 70]
 [21 99 39]]
X: [[0.46332405]
 [0.1913527 ]
 [0.60853755]
 [0.48401268]
 [0.10194666]]
NumPy 2*X: [[0.9266481 ]
 [0.3827054 ]
 [1.2170751 ]
 [0.96802535]
 [0.20389332]]
N(0,1) Y: [[-0.70897851]
 [-0.57874412]
 [ 2.35865587]
 [-0.51573855]
 [-1.620678  ]]
Python list*2 [1, 2, 3, 1, 2, 3]
[2, 4, 6]


In [35]:
arr8=np.arange(10).reshape((5,2))
print(arr8)
print('访问元素',arr8[0,1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
访问元素 1


In [38]:
#提取行
print(arr8[1:3,:])

[[2 3]
 [4 5]]


In [7]:
# 深度复制
arr9=np.arange(10)
arr10=arr9.copy()
arr10[0]=100
print(arr9)
print(arr10)
# 列向量
print(arr9.reshape(-1,1))
# 矩阵转置
print(arr9.reshape(2,5).T)

[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [10]:
# 提取矩阵列
arr11=arr9.reshape(2,5)
print(arr11)
print(arr11[:,2:4])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[2 3]
 [7 8]]


In [15]:
# 转换为矩阵
print(arr9)
print(arr9.reshape(2,-1))
print(arr9.reshape((2,-1)))
# 转换为向量
print(arr9.reshape(2,5).reshape(10))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr12=np.arange(4).reshape((2,2))
# 将列表中的数组们拼接
print(np.concatenate([arr12, np.arange(4,10).reshape((2,3))], axis=1))
print(arr12.shape)

[[0 1 4 5 6]
 [2 3 7 8 9]]
(2, 2)


In [30]:
arr13=np.array([[1,2,3],[4,5,6]])
print(arr13)
arr14=np.arange(6).reshape(2,3)
print(arr14)
# 作为行拼接
print(np.concatenate([arr13,arr14], axis=0))
# 作为列拼接
print(np.concatenate([arr13,arr14], axis=1))

[[1 2 3]
 [4 5 6]]
[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]
 [0 1 2]
 [3 4 5]]
[[1 2 3 0 1 2]
 [4 5 6 3 4 5]]
